FROM python:slim

RUN apt-get update && apt-get install -y \
    build-essential \
    mariadb-client \
    libmariadb-dev

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80" ]
